######### Basic Settings #########
basic:
    prefix: reproduce
    device: '3'
    seed: [0] 
    num_workers: 4

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: twoview_dldataset_all

    ret_valid: true

    # Method Choises: 
    method: balsup_mocov2

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet50
    save_models: true # if true, programm will save model's weights during incremental train

    img_size: 100
    save_name: res50_100x100_lr0.001_epoch500_1024_batch32
    
######### Method's Hyperparameters #########
special:
    K: 1024
    m: 0.999
    T: 0.07
    

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100    
    twoview_dldataset_all:
        resnet50:             
            epochs: 500
            batch_size: 32

            lrate: 0.001
            # opt_type: adam
            opt_type: sgd
            weight_decay: 0.0001
            scheduler: cos
            
            criterion: ce
        
        resnet34:             
            epochs: 500
            batch_size: 32

            lrate: 0.001
            # opt_type: adam
            opt_type: sgd
            weight_decay: 0.0001
            scheduler: cos
            
            criterion: ce
