######### Basic Settings #########
basic:
    prefix: reproduce
    device: '6,7'
    seed: [0] 
    num_workers: 4

    # Dataset Choises: dldataset_all, bal_dldataset_all
    dataset: dldataset_all

    ret_valid: true

    # Method Choises: 
    method: finetune

    # Backbone Choises: resnet18, resnet18_cbam, resnet50, resnet101
    backbone: resnet101
    pretrained: true
    # pretrain_path: pretrain_models/imagenet200_resnet18_cbam_pretrained.pth
    freeze: false
    save_models: true # if true, programm will save model's weights during incremental train

    img_size: 100
    save_name: res101_bal_100x100_focal_adam
    
######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:    
    dldataset_all:
        resnet50:             
            epochs: 150
            batch_size: 16

            lrate: 0.0001
            # opt_type: adam
            opt_type: sgd
            weight_decay: 0.0002            

            # scheduler: multi_step # cos
            # milestones: [40, 80, 120]
            # lrate_decay: 0.1       

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75
        
        resnet101:             
            epochs: 150
            batch_size: 16

            lrate: 0.0001
            opt_type: adam
            # opt_type: sgd
            # weight_decay: 0.0002

            scheduler: multi_step # cos
            milestones: [40, 80, 120]
            lrate_decay: 0.1

            # criterion: ce
            criterion: focal
            gamma: 5
            alpha: 0.75
    
    bal_dldataset_all:
        resnet50:             
            epochs: 150
            batch_size: 16

            lrate: 0.0001
            # opt_type: adam
            opt_type: sgd
            weight_decay: 0.0002            

            # scheduler: multi_step # cos
            # milestones: [40, 80, 120]
            # lrate_decay: 0.1       

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75
        
        resnet101:             
            epochs: 150
            batch_size: 16

            lrate: 0.0001
            opt_type: adam
            # opt_type: sgd
            # weight_decay: 0.0002

            scheduler: multi_step # cos
            milestones: [40, 80, 120]
            lrate_decay: 0.1

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75
