######### Basic Settings #########
basic:
    prefix: reproduce
    device: '2'
    seed: [0] 
    num_workers: 4

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: bal_dldataset_all

    ret_valid: true

    # Method Choises: 
    method: finetune
    nlp_num: 0

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet101
    pretrained: true
    pretrain_path: logs/mocov2/res101_100_lr0.0001_epoch500_batch32/moco_encoder_q.pkl
    freeze: true
    save_models: true # if true, programm will save model's weights during incremental train

    img_size: 100
    save_name: retrain_mocov2_res101_100_lr0.0001_epoch500_batch32
    
######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:
    dldataset_all:
        resnet50:             
            epochs: 100
            batch_size: 16

            lrate: 0.0001
            opt_type: adam
            scheduler: multi_step # cos
            milestones: [40, 80]
            lrate_decay: 0.1          

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75
        
        resnet101:             
            epochs: 100
            batch_size: 16

            lrate: 0.0001
            opt_type: adam
            scheduler: multi_step # cos
            milestones: [40, 80]
            lrate_decay: 0.1          

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75
    
    bal_dldataset_all:
        resnet34:             
            epochs: 100
            batch_size: 16

            lrate: 0.0001
            opt_type: adam
            scheduler: multi_step # cos
            milestones: [40, 80]
            lrate_decay: 0.1          

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75

        resnet50:             
            epochs: 100
            batch_size: 16

            lrate: 0.0001
            opt_type: adam
            scheduler: multi_step # cos
            milestones: [40, 80, 120]
            lrate_decay: 0.1          

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75
        
        resnet101:             
            epochs: 100
            batch_size: 16

            lrate: 0.0001
            opt_type: adam
            scheduler: multi_step # cos
            milestones: [40, 80]
            lrate_decay: 0.1          

            criterion: ce
            # criterion: focal
            # gamma: 5
            # alpha: 0.75
            
